### ISSUE TITLE
Error reported without newline between config nodes

### ISSUE THREAD

**Issue by zer0Kerbal** [KSP-CKAN/KSPMMCfgParser#11]
I believe the space .cfg is correct in syntax.

workflow result:

Error: GameData/KlockheedMartian/SpecialPartsDivision/Spaces/Skylab/part.cfg:1:1: Unexpected 'M<0x4D>'

[File flagged](https://github.com/zer0Kerbal/SpecialPartsDivision/blob/master/GameData/KlockheedMartian/SpecialPartsDivision/Spaces/Skylab/part.cfg)

`[Validate-cfg-files: GameData/KlockheedMartian/SpecialPartsDivision/Spaces/Skylab/part.cfg#L1](https://github.com/zer0Kerbal/SpecialPartsDivision/commit/cc44253b638e9744e6418a0050033be1650e339d#annotation_3426042474)
GameData/KlockheedMartian/SpecialPartsDivision/Spaces/Skylab/part.cfg:1:1: Unexpected 'M<0x4D>'`

**Comment by HebaruSan** [comment]
The file apparently looked like this when that error was reported, with no line break between `}` and the next node identifier:

https://github.com/zer0Kerbal/SpecialPartsDivision/commit/9fe217c2d1ec080a931ed574b1a4a954a395ad3a

![image](https://user-images.githubusercontent.com/1559108/167313944-7a61aebe-f4ae-4ac6-a27d-6bf3d14ca825.png)

I think we want to keep flagging that. Thanks for the report.

**Comment by zer0Kerbal** [comment]
I edited the file and changed that - reran and it still flagged the file.
`[Validate-cfg-files: GameData/KlockheedMartian/SpecialPartsDivision/Spaces/Skylab/part.cfg#L1](https://github.com/zer0Kerbal/SpecialPartsDivision/commit/cc44253b638e9744e6418a0050033be1650e339d#annotation_3426098917)
GameData/KlockheedMartian/SpecialPartsDivision/Spaces/Skylab/part.cfg:1:1: Unexpected 'M<0x4D>'`

plus it is flagging line 1, pos 1 - (unless the workflow only reports that file position)

**Comment by HebaruSan** [comment]
I checked out your repo and ran the validator locally and nothing was reported. If you just clicked the re-run button in GitHub, that will run it against the old version of the file.

**Comment by zer0Kerbal** [comment]
yep - did just that after I suspected just that.

**Comment by zer0Kerbal** [comment]
hopefully it will provide more user friendly feedback in the future.
