### ISSUE TITLE
[Bug] MM now supports * in node names as of 4.2.2 but Validator chokes on it

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/KSPMMCfgParser#14]
Just hit that here: https://github.com/KSP-RO/RP-0/runs/6952335871?check_suite_focus=true

I'm not sure about the end of stream, but the other is clearly because of `@*,* {` which in 4.2.1 and below was invalid but is valid now.

Sorry!

**Comment by HebaruSan** [comment]
The end of stream thing is because there's a missing close brace around line 444 of `Programs.cfg`:

![image](https://user-images.githubusercontent.com/1559108/174464418-fee042fc-a07b-493e-ad2f-82181376dd8a.png)

Added a review comment on KSP-RO/RP-0#1693 for that.

**Comment by NathanKell** [comment]
Oooh, thanks! :)

**Comment by NathanKell** [comment]
And sorry, didn't know whether it should be Bug or Suggestion tbh? But I saw you tagged as enhancement so...as long as you decided how to deal with it properly. :)

**Comment by HebaruSan** [comment]
Capturing the usage for future reference during dev:

https://github.com/KSP-RO/RP-0/blob/fc9ca4ed04ced226026904a51fb2d1c1b9e4f1aa/GameData/RP-0/Strategies/LocPatches.cfg

```
@Localization:HAS[~RP0conf[True]]
{
	@*,*
	{
		!#autoLOC_460808 = Burn Time Est

		!#autoLOC_439627 = Active Programs: <<1>> [Max: <<2>>]
		!#autoLOC_900144 = Max Active Programs: [StrategyCount]
```

~~It seems like the intention is to override every language with English strings, defeating the purpose of localization.~~ Wait, no; the `!` means these are _deletions_?
