### ISSUE TITLE
[Bug]: KSPMMCfgValidator fails to load log4net or a dependency

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-CKAN/KSPMMCfgParser#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

ubuntu-latest Workflow runner

### CKAN Version

N/A

### Games

KSP 1

### Game Version

N/A

### Describe the bug

When running the validator in a GitHub workflow, it crashes with a `FileNotFoundException` 

### Steps to reproduce

Run any workflow using the validator.

### Relevant log output

https://github.com/KSP-RO/RealismOverhaul/actions/runs/7405049853/job/20167921570?pr=2932#step:7:15

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'log4net, Version=2.0.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies.
File name: 'log4net, Version=2.0.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'
Error:  FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'log4net, Version=2.0.[15](https://github.com/KSP-RO/RealismOverhaul/actions/runs/7405049853/job/20167921570?pr=2932#step:7:16).0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies.
File name: 'log4net, Version=2.0.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'
```

**Comment by HebaruSan** [comment]
Looks like a weird Docker container problem. The correct repacked file is 1.2 MB:

```
$ ls -sh _build/KSPMMCfgValidator/Debug/bin/net48/Repack/KSPMMCfgValidator.exe
1.2M _build/KSPMMCfgValidator/Debug/bin/net48/Repack/KSPMMCfgValidator.exe
```

But the container has just this 12 KB stub:

```
# ls -sh /usr/local/bin
total 12K
12K KSPMMCfgValidator.exe
```

Which matches the size of the non-repacked file:

```
$ ls -sh _build/KSPMMCfgValidator/Debug/bin/net48/
total 1.4M
 60K CommandLine.dll                380K Microsoft.Build.Utilities.Core.dll
8.0K ILRepack.log                    32K Microsoft.VisualStudio.Setup.Configuration.Interop.dll
 44K KSPMMCfgParser.dll              96K ParsecSharp.dll
 36K KSPMMCfgParser.xml                0 Repack
 12K KSPMMCfgValidator.exe          296K System.Collections.Immutable.dll
   0 KSPMMCfgValidator.exe.config    36K System.Runtime.InteropServices.RuntimeInformation.dll
4.0K KSPMMCfgValidator.xml          264K log4net.dll
120K Microsoft.Build.Framework.dll
```

So we're pulling the wrong file into the image...

**Comment by HebaruSan** [comment]
... aha. Missed a spot when the repack output path changed.

https://github.com/KSP-CKAN/KSPMMCfgParser/blob/38e5173291498e748cf7d23dd3b4b1ae31bd40bc/.github/workflows/release.yml#L76

**Comment by HebaruSan** [comment]
@StonesmileGit can you please try re-running the workflow? The Docker image has been updated (ae7837cb8f322245347e1af29e0768c4e04110d2) with what should be a fix.

**Comment by StonesmileGit** [comment]
New error:
https://github.com/KSP-RO/RealismOverhaul/actions/runs/7405049853/job/20185911553#step:7:15

**Comment by HebaruSan** [comment]
Thanks. That message makes no sense to me, but at least I am able to reproduce it in the container.

```
# mono /usr/local/bin/KSPMMCfgValidator.exe

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'KSPMMCfgValidator.KSPMMCfgValidator' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x04000009, due to: Could not load type of field 'KSPMMCfgValidator.KSPMMCfgValidator+<>c:<>9__1_1' (1) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:/usr/local/bin/KSPMMCfgValidator.exe type:<>c member:(null)
   --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'KSPMMCfgValidator.KSPMMCfgValidator' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x04000009, due to: Could not load type of field 'KSPMMCfgValidator.KSPMMCfgValidator+<>c:<>9__1_1' (1) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:/usr/local/bin/KSPMMCfgValidator.exe type:<>c member:(null)
   --- End of inner exception stack trace ---
```

**Comment by HebaruSan** [comment]
Ahh, `apt install mono-complete` fixes it, so there must be some dependency we're missing.

... After installing `mono-complete`'s dependencies in smaller subsets, it works if `mono-roslyn` and `mono-devel` are installed, and it doesn't work if they're not. Which is troubling since I think that's the C# compiler, and we shouldn't need to install a compiler to run an already-compiled app. It also pulls in a huge pile of dependencies (none of which solve the problem on their own), so the Docker image will be bloated again. But if we have to, then we have to.

```
REPOSITORY                         TAG       IMAGE ID       CREATED             SIZE
kspckan/kspmmcfgvalidator          latest    b235ab1106a1   20 hours ago        197MB
cfgvalidator_test                  latest    ddda9bf1fa99   57 seconds ago      541MB
```

**Comment by HebaruSan** [comment]
@StonesmileGit try again now?

**Comment by StonesmileGit** [comment]
Fixed!
